### ISSUE TITLE
BST clear/empty function

### ISSUE THREAD

**Issue by theorangepotato** [brandon-a/CIS-22C-Group-Project#16]
I want to add an open file option, so if you could implement something that clears out the BSTs so that they can be rebuilt, that would be great! I've already added it to the HashTable.

**Comment by brandon-a** [comment]
I already have a clear function that does this, it can be called as such:

``` C++
keyBST.clear();
secBST.clear();
```

**Comment by theorangepotato** [comment]
Awesome!
