### ISSUE TITLE
InputOutput?

### ISSUE THREAD

**Issue by theorangepotato** [brandon-a/CIS-22C-Group-Project#17]
Do we need the InputOutput class, since we're using member functions? If not, we can remove it from the next commit.

**Comment by Jasko-A** [comment]
We do not need it since it is in member functions, having a class for that
would be unnecessary.

Jasmin

**Comment by michaelsmelik** [comment]
I will remove it. I am currently working on it. Austin can you help me with the rehash function that I need to write? I either need a way to traverse your hash table or some other way to get the elements from the hash in the order that they are in.

**Comment by theorangepotato** [comment]
I believe the commit I just made will be helpful. I implemented a way to rehash the table. I also put a small member function in main so that we could implement an Open File option. But yeah, check out that commit, the member function is called rehash()

**Comment by michaelsmelik** [comment]
will look at it
