### ISSUE TITLE
Program won't compile. Getting linker errors

### ISSUE THREAD

**Issue by brandon-a** [brandon-a/CIS-22C-Group-Project#18]
mainMembers.obj : error LNK2005: _main already defined in main.obj

Not sure how to fix this, anyone have any ideas?

**Comment by brandon-a** [comment]
For now I continued to use main to work on the project because I cannot get it to work with mainMembers.cpp

**Comment by theorangepotato** [comment]
The answer to fix it involves header files and stuff. Ahmed took a while figuring out. I think the solution now is to just scrap mainMembers and just have a separate file for Ahmed and Mikhail. That's how it has to be in the end anyway.

**Comment by ashalan1998** [comment]
You have to include a header file for mainMembers.h with all function
prototypes from mainMembers.cpp. This only worked for me when I used
CodeBlocks though. It gives link errors with xCode and Visual Studio.

**Comment by theorangepotato** [comment]
Technically it also works if you just use a straight compiler instead of an IDE. At least with g++...

**Comment by brandon-a** [comment]
So when we present in class we're using CodeBlocks?

**Comment by ashalan1998** [comment]
I'm pretty when we present in class we will be using a .exe file. No IDE needed. At least that's what I understood from the directions.
