### ISSUE TITLE
Implement 4 lists from the requirements.

### ISSUE THREAD

**Issue by brandon-a** [brandon-a/CIS-22C-Group-Project#20]
###### List (sub menu with below options)
- List unsorted data // details will be given next week
- List data sorted by the primary key
- List data sorted by the secondary key
- Special print, as an indented list // details will be given next week

**Comment by ashalan1998** [comment]
The list submenu is included in the list header file. I added the function
call to the menu in main but commented it out because I can't get the
program to compile so I can't test it.

On Mon, Nov 30, 2015 at 12:11 PM, Brandon Archbold <notifications@github.com

**Comment by ashalan1998** [comment]
I uncommented the calls to Search Manager and List Manager and they work. Im going to go back and add the special print as an option but for now the list manager sub menu and search manager sub menu should work.
