### ISSUE TITLE
Binary Tree In Order function seems to be broken

### ISSUE THREAD

**Issue by ashalan1998** [brandon-a/CIS-22C-Group-Project#21]
The inOrderStack function doesn't seem to work. The program just freezes whenever it's called.

I tried making a different recursive inOrder function in BinaryTree and so far its working but I'm getting out of order Food Key's when they should have been in order.

This is the inOrder function I'm using (didn't commit it to the project): 

``` C++
void inOrder(void visit(Food *)) const {_inorder(visit, rootPtr);}

void BinaryTree::_inorder(void visit(Food *), BinaryNode * nodePtr) const{
        if (nodePtr != nullptr)
    {
        Food * food = nodePtr->getItem();
            _inorder(visit, nodePtr->getLeftPtr());
        visit(food);
        _inorder(visit, nodePtr->getRightPtr());
    }
} 
```

Here's the output I'm getting when I use the above inOrder function on the keyBST tree in main 

```
    Food Key  : 42204
    Food Key  : 42161
    Food Key  : 42171
    Food Key  : 42155
    Food Key  : 42205
    Food Key  : 42178
    Food Key  : 42189
    Food Key  : 42157
    Food Key  : 42200
    Food Key  : 42173
    Food Key  : 42196
    Food Key  : 42185
    Food Key  : 42188
    Food Key  : 42186
    Food Key  : 42193
    Food Key  : 42158
    Food Key  : 42192
    Food Key  : 42182
    Food Key  : 42187
    Food Key  : 42181
    Food Key  : 42190
    Food Key  : 42227
    Food Key  : 42179
    Food Key  : 42183
    Food Key  : 42184
```

Really not sure why this is happening.

**Comment by michaelsmelik** [comment]
That means that the bst is in the wrong order I think. And if that is the problem that means that the bst gets populated incorrectly

**Comment by brandon-a** [comment]
The BST by key is in the correct order now. The BST by name is not in the correct order and I cannot figure out why.
