### ISSUE TITLE
ReHash

### ISSUE THREAD

**Issue by michaelsmelik** [brandon-a/CIS-22C-Group-Project#22]
Austin your reHash function currently just deletes the old hash and creates a brand new one but without filling it in. How could we make it so that the new hash gets populated as well?

**Comment by brandon-a** [comment]
Since the hash table is an array, it cannot be rehashed without recreating the array since arrays cannot be resized.

**Comment by theorangepotato** [comment]
Well, the point is that it can be filled it by calling the main function createADTs. The hash table, like the BST, is only ever created by inserting all of the Food objects. Unless you wanted an option to make the same table with a larger array?

**Comment by theorangepotato** [comment]
We decided that this is best solved by using the hashtable by pointer.
