### ISSUE TITLE
Open File/Food arr

### ISSUE THREAD

**Issue by theorangepotato** [brandon-a/CIS-22C-Group-Project#30]
I thought we agreed that we do not need a food array? Should I remove that?

**Comment by Jasko-A** [comment]
Then how will we be writing to the file? If I remember that is what we are
using it for.

**Comment by theorangepotato** [comment]
What, why? Does it need to be read out in the same order it came in?

**Comment by michaelsmelik** [comment]
I am sorry about adding it. We don't need it. Please delete it.

**Comment by Jasko-A** [comment]
No we need it to read out the the list inorder, I believe. If it works
without it then nevermind, as long as it is being written out to a file.

**Comment by theorangepotato** [comment]
Oh, okay. I see. There are two food arrays. I was talking about the one used in the createADTs that was an artifact of an old commit. I believe you are talking about the one in the printToFile function, right? As far as I can tell, that's fine.

**Comment by michaelsmelik** [comment]
Jasmin you are thinking about the wrong array. I added an unsorted array that we should get rid of.

**Comment by Jasko-A** [comment]
Ohh, my bad I was talking about the one in function printToFile.

**Comment by michaelsmelik** [comment]
The one that is in createADT should be deleted

**Comment by Jasko-A** [comment]
Yeah l see, my bad guys, misunderstanding on my part

**Comment by theorangepotato** [comment]
Alright, I will remove it in the commit I will push in a few minutes.
