### ISSUE TITLE
toUpper

### ISSUE THREAD

**Issue by theorangepotato** [brandon-a/CIS-22C-Group-Project#31]
When we search by secondary key, we should convert the search string to all caps so that someone who is searching doesn't have to hold shift or use caps lock or anything.

I'm not sure exactly whose job this is, but its @ashalan1998 's function, so I'm tagging you.

**Comment by Jasko-A** [comment]
Yes that is a very good idea

**Comment by ashalan1998** [comment]
Just added that. If I understood correctly, I changed it so that typing in "apple" will search for "APPLE".

**Comment by Jasko-A** [comment]
Did we do the same thing for wheb we add an item

**Comment by theorangepotato** [comment]
Awesome. And you are right, @Jasko-A , we should do the same on input.

**Comment by ashalan1998** [comment]
No, but I can do that.

**Comment by ashalan1998** [comment]
Ok, did the same for input. When adding Food objects, entering in "apple" will be saved as "APPLE".

**Comment by Jasko-A** [comment]
Awesome go ahead and do that

**Comment by theorangepotato** [comment]
@ashalan1998 I don't see the commit yet?

**Comment by ashalan1998** [comment]
Thats weird, I did commit twice.
