### ISSUE TITLE
Null value = -?

### ISSUE THREAD

**Issue by theorangepotato** [brandon-a/CIS-22C-Group-Project#32]
I liked the idea from one of the groups yesterday where if no data is provided, a negative number (-1) is placed in the variable so that we can differentiate between a value of 0 and no data. I would just write and push it, but this seems like a change everyone should at least be aware of, if not have input on. So, should I implement this?

**Comment by brandon-a** [comment]
I agree this is a good idea.

**Comment by theorangepotato** [comment]
I believe my most recent commit just implemented this.
