### ISSUE TITLE
Required documentation for final submission.

### ISSUE THREAD

**Issue by brandon-a** [brandon-a/CIS-22C-Group-Project#34]
We need to make sure our functions have all of the required documentation for the assignment. Add a comment to the top of your header files explaining your part in the program and how your file interacts with the rest of the program.

[Required documentation.](https://github.com/brandon-a/CIS-22C-Group-Project/files/51545/Microsoft.Word.-.TeamProject_Part2.pdf)

**Comment by Jasko-A** [comment]
This has been complete
