### ISSUE TITLE
Final edits for UML diagram and Data Structure Diagram

### ISSUE THREAD

**Issue by Jasko-A** [brandon-a/CIS-22C-Group-Project#5]
Mention anything we might have left out from last time, I will be creating these after 10:30 today once my math class finishes. :+1:

**Comment by brandon-a** [comment]
Do you still need help on this? Or are we all good?

**Comment by Jasko-A** [comment]
Some more help on this would be good. Add anything you guys think i am missing. The diagrams are on the powerpoint in google drive.

**Comment by Jasko-A** [comment]
This has been complete. Check power point for details. I will put the final touches to it tomorrow when we get it completed. I will go ahead and close this
